"""initial schema

Revision ID: 3b9be4d3b3fa
Revises: 
Create Date: 2026-10-05 04:30:18.494238
"""
from alembic import op
import sqlalchemy as sa


revision = '3b9be4d3b3fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_provider_configs',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ai_usage',
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('task', sa.String(length=60), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('input_units', sa.Integer(), nullable=False),
    sa.Column('output_units', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('fallback', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_task'), ['task'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('brands',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('whatsapp', sa.String(length=32), nullable=True),
    sa.Column('primary_color', sa.String(length=16), nullable=False),
    sa.Column('secondary_color', sa.String(length=16), nullable=False),
    sa.Column('font', sa.String(length=64), nullable=False),
    sa.Column('catalog_style', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_brands_user_id'), ['user_id'], unique=False)

    op.create_table('catalogs',
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='catalogstatus', native_enum=False, length=20), nullable=False),
    sa.Column('theme', sa.Enum('minimal', 'editorial', 'street', 'premium', 'colorful', name='catalogtheme', native_enum=False, length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalogs_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalogs_slug'), ['slug'], unique=True)

    op.create_table('products',
    sa.Column('catalog_id', sa.String(length=32), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('stock_mode', sa.Enum('tracked', 'unlimited', 'out_of_stock', name='stockmode', native_enum=False, length=20), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('subcategory', sa.String(length=80), nullable=True),
    sa.Column('color', sa.String(length=60), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('size', sa.String(length=60), nullable=True),
    sa.Column('material', sa.String(length=80), nullable=True),
    sa.Column('fit', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('draft', 'processing', 'review', 'published', 'archived', name='productstatus', native_enum=False, length=20), nullable=False),
    sa.Column('primary_asset_type', sa.Enum('original', 'clean', 'model', 'lifestyle', 'video', 'thumbnail', name='assettype', native_enum=False, length=20), nullable=False),
    sa.Column('ai_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_catalog_id'), ['catalog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=False)

    op.create_table('ai_jobs',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=True),
    sa.Column('task', sa.String(length=60), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='jobstatus', native_enum=False, length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_jobs_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('product_assets',
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('original', 'clean', 'model', 'lifestyle', 'video', 'thumbnail', name='assettype', native_enum=False, length=20), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=600), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_assets_product_id'), ['product_id'], unique=False)

    op.create_table('product_variants',
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('size', sa.String(length=30), nullable=True),
    sa.Column('color', sa.String(length=60), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variants_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variants_product_id'))

    op.drop_table('product_variants')
    with op.batch_alter_table('product_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_assets_product_id'))

    op.drop_table('product_assets')
    with op.batch_alter_table('ai_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_ai_jobs_product_id'))

    op.drop_table('ai_jobs')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.drop_index(batch_op.f('ix_products_catalog_id'))

    op.drop_table('products')
    with op.batch_alter_table('catalogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalogs_slug'))
        batch_op.drop_index(batch_op.f('ix_catalogs_brand_id'))

    op.drop_table('catalogs')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_user_id'))
        batch_op.drop_index(batch_op.f('ix_brands_slug'))

    op.drop_table('brands')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_task'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_provider'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_created_at'))

    op.drop_table('ai_usage')
    op.drop_table('ai_provider_configs')
    # ### end Alembic commands ###
