"""product published_at and usage product_id

Revision ID: a58d33f00a3f
Revises: 3b9be4d3b3fa
Create Date: 2026-10-05 12:01:39.809974
"""
from alembic import op
import sqlalchemy as sa


revision = 'a58d33f00a3f'
down_revision = '3b9be4d3b3fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_ai_usage_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('published_at')

    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_product_id'))
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
