"""brand models

Revision ID: 3f17fcc9440b
Revises: a58d33f00a3f
Create Date: 2026-10-05 12:41:54.126910
"""
from alembic import op
import sqlalchemy as sa


revision = '3f17fcc9440b'
down_revision = 'a58d33f00a3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_models',
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('age_range', sa.String(length=30), nullable=True),
    sa.Column('style', sa.String(length=60), nullable=True),
    sa.Column('reference_images', sa.JSON(), nullable=True),
    sa.Column('prompt_template', sa.Text(), nullable=True),
    sa.Column('provider_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brand_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_models_brand_id'), ['brand_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_models_brand_id'))

    op.drop_table('brand_models')
    # ### end Alembic commands ###
